/* =============================================================================
 *  patsy-names.js  —  v3.20.24
 *
 *  Patsies, in the Ratiocinatory, are the bodies commissioned to absorb
 *  cognitive blame on behalf of chartered panels of inquiry. In code they
 *  used to be abstract counters (state.patsiesJunior, etc.). They now have
 *  NAMES — a pool of 120+ — so the UI can, if it wishes, surface a
 *  commissioned individual rather than a tally on a page.
 *
 *  Names are written to lean "bureaucratic ghost" — old-register
 *  Midwestern, forgotten Mid-Atlantic, retired stationery catalogue. A
 *  patsy is someone whose letterhead nobody at the office quite
 *  remembers hiring.
 *
 *  Usage:
 *    PatsyNames.list()           -> full flat list (array of strings)
 *    PatsyNames.count()          -> total number in the pool (>= 120)
 *    PatsyNames.pickStable(seed) -> deterministic pick for a seed integer
 *    PatsyNames.pickRandom()     -> random pick, per-call
 *
 *  This module writes no state. It is a static name library.
 * ============================================================================= */

(function () {
  'use strict';

  // First names: old-register, vaguely Mid-Atlantic, flat-affected.
  var FIRSTS = [
    'Delmar', 'Ellsworth', 'Harvey', 'Marvin', 'Clyde', 'Orville', 'Leland',
    'Dwight', 'Howard', 'Sheldon', 'Raymond', 'Clifford', 'Wendell', 'Kenneth',
    'Bernard', 'Gaylord', 'Herbert', 'Milton', 'Russell', 'Warren', 'Wilbur',
    'Ernest', 'Stanley', 'Ralph', 'Melvin', 'Arnold', 'Irving', 'Leonard',
    'Willard', 'Vernon', 'Carlton', 'Hubert', 'Roland', 'Merle', 'Elmer',
    'Lyle', 'Floyd', 'Otis', 'Hiram', 'Ezra', 'Lowell', 'Cletus', 'Rudolph',
    'Edwin', 'Mervyn', 'Thaddeus', 'Percival', 'Archibald', 'Cornelius',
    'Gertrude', 'Mildred', 'Bernice', 'Dorothy', 'Imogene', 'Eunice', 'Vera',
    'Wilhelmina', 'Edna', 'Agnes', 'Hazel', 'Mabel', 'Hortense', 'Henrietta',
    'Minerva', 'Opal', 'Lavinia', 'Beulah', 'Phyllis', 'Norma', 'Enid',
    'Myrna', 'Doris', 'Olive', 'Pearl', 'Ethel', 'Leona', 'Cordelia',
    'Prudence', 'Ingrid', 'Myra'
  ];

  // Surnames: long, forgettable, often starch or textile-adjacent.
  var LASTS = [
    'Pettibone', 'Ashwood', 'Quimby', 'Fenstermacher', 'Huckaby', 'Drinkwater',
    'Wooster', 'Plimpton', 'Crabtree', 'Halliwell', 'Thistlethwaite',
    'Bramwell', 'Lockridge', 'Ackerman', 'Ellsbury', 'Ormsby', 'Dalrymple',
    'Fothergill', 'Pennywhistle', 'Wickersham', 'Osgood', 'Applegate',
    'Bickford', 'Tredinnick', 'Featherington', 'Hazleton', 'Bickerstaff',
    'Dunwoody', 'Marchbanks', 'Kettlewell', 'Pinkerton', 'Hemsworth',
    'Winterbottom', 'Lockhart', 'Stillwell', 'Pendergast', 'Worthington',
    'Kilbride', 'Mortlake', 'Trelawney', 'Halpenny', 'Scrimgeour',
    'Gilchrist', 'Rothermel', 'Stamper', 'Easterbrook', 'Hawkinberry',
    'Quimbleton', 'Frobisher'
  ];

  // Construct a deterministic flat list of 120 full names so that the
  // pool is STABLE across page loads (picking "patsy #42" always returns
  // the same person). Pairs are generated by stepping through firsts and
  // surnames at co-prime offsets so siblings don't repeat.
  function buildPool() {
    var pool = [];
    var F = FIRSTS.length;
    var L = LASTS.length;
    // 120 deterministic pairs.
    for (var i = 0; i < 120; i++) {
      var f = FIRSTS[i % F];
      var l = LASTS[(i * 7) % L];
      pool.push(f + ' ' + l);
    }
    // A few hand-tuned flourishes to avoid the list feeling auto-generated.
    pool.push('Delmar Pettibone, Jr.');
    pool.push('Mrs. Ashwood-Quimby');
    pool.push('Kenneth "Ken" Kettlewell');
    pool.push('H. Lowell Easterbrook');
    pool.push('Phyllis (file pending)');
    pool.push('Pearl of Accounts Receivable');
    pool.push('Thaddeus the Younger');
    pool.push('Arnold, no known last name');
    return pool;
  }

  var POOL = buildPool();

  function list() { return POOL.slice(); }
  function count() { return POOL.length; }

  function pickStable(seed) {
    var n = POOL.length;
    var s = (typeof seed === 'number' && isFinite(seed)) ? Math.floor(seed) : 0;
    var idx = ((s % n) + n) % n;
    return POOL[idx];
  }

  function pickRandom() {
    return POOL[Math.floor(Math.random() * POOL.length)];
  }

  window.PatsyNames = {
    list: list,
    count: count,
    pickStable: pickStable,
    pickRandom: pickRandom
  };

})();
